CREATE TABLE quest(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(100) NOT NULL UNIQUE,
    ans1 VARCHAR(100) NOT NULL,
    ans2 VARCHAR(100) NOT NULL,
    ans3 VARCHAR(100) NOT NULL,
    ans4 VARCHAR(100) NOT NULL,
    correctAns VARCHAR(100) NOT NULL
);